language: go
go:
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/skycoin/net
  - go get golang.org/x/tools/cmd/cover
  - go get -t ./...
script:
  - go test ./...
  - bash coverage.sh
